/**
 * fireyejsRunner — Token generation and infrastructure.
 *
 * bx-ua: Generated by bxUaGenerator.ts — a pure Node.js implementation
 *   that replicates the AWSC fireyejs.js token format without Playwright.
 *   Matches the real token: "231!" + base64(900 bytes) = 1204 chars.
 *
 * bx-pp: SHA-256 payload hash fallback (opcode 58 needs real AWSC).
 *
 * Cookie refresh: Playwright browser navigates chat.qwen.ai to refresh
 *   acw_tc and other WAF session cookies. This is the only remaining
 *   browser dependency — runs once per 30 min per account.
 */
import { resolve } from 'path';
import { resolveChromeExecutable } from '../utils/browserBinary.ts';
import { getBxUaToken } from './bxUaGenerator.ts';
import { logStore } from './logStore.ts';
import { QWEN_API_BASE } from './qwen.ts';
import { tokenCache } from './tokenCache.ts';

// ─── Constants ───────────────────────────────────────────────────────────────

const BX_UA_TTL_MS = 15 * 60 * 1000; // 15 min
const DEFAULT_FIREYEJS_PATH = resolve(process.cwd(), 'fireyejs.js');

// ─── bx-ua generation ────────────────────────────────────────────────────────
// Pure Node.js via bxUaGenerator.ts — no browser needed.
// Token matches real AWSC fireyejs.js output format exactly.

/**
 * Generate (or retrieve cached) bx-ua token.
 *
 * @returns The bx-ua token string (e.g. "231!<base64>") or null
 */
export async function generateBxUa(): Promise<string | null> {
  // Check shared cache first
  const cached = tokenCache.get('bx-ua');
  if (cached) return cached;

  try {
    const token = getBxUaToken();

    if (token && token.startsWith('231!')) {
      tokenCache.set('bx-ua', token, BX_UA_TTL_MS);
      logStore.log('info', 'fireyejs', `bx-ua generated via bxUaGenerator (${token.length} chars, TTL ${BX_UA_TTL_MS / 60000} min)`);
      return token;
    }

    logStore.log('warn', 'fireyejs', 'bx-ua generated but invalid format');
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('error', 'fireyejs', `bx-ua generation failed: ${msg}`);
    return null;
  }
}

// ─── bx-pp generation (Phase C) ──────────────────────────────────────────────

/**
 * Generate a bx-pp per-request signature.
 *
 * bx-pp is normally generated by fireyejs opcode 58. Since the real fireyejs
 * requires the AWSC browser environment, we use a SHA-256 payload hash as
 * fallback. Testing confirmed this works: the models endpoint returned 200.
 *
 * TODO: reverse-engineer opcode 58 from fireyejs.js for bx-pp generation
 * that matches what the real browser produces.
 */
export async function generateBxPp(payload?: string): Promise<string | null> {
  // ponytail: hash fallback until opcode 58 reverse-engineered
  try {
    const data = new TextEncoder().encode(payload || Date.now().toString());
    const hash = await crypto.subtle.digest('SHA-256', data);
    const hashHex = Array.from(new Uint8Array(hash))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join('')
      .slice(0, 32);
    logStore.log('debug', 'fireyejs', 'bx-pp generated (hash fallback)');
    return hashHex;
  } catch {
    return null;
  }
}

// ─── Cookie refresh via browser ─────────────────────────────────────────────

let playwrightBrowser: any = null;

export async function getBrowser(): Promise<any> {
  // `isConnected()` — not `_closed`. Playwright's Browser has no `_closed`
  // property (it is `undefined` both before and after close), so that guard
  // never detected a dead browser and would hand back a broken handle.
  if (playwrightBrowser?.isConnected()) {
    return playwrightBrowser;
  }
  // Pass executablePath explicitly: Playwright's own pinned revision may be
  // absent from the cache, which throws "Executable doesn't exist at ...".
  const executablePath = resolveChromeExecutable();
  const { chromium } = await import('playwright');
  playwrightBrowser = await chromium.launch({
    headless: true,
    executablePath,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
  });
  return playwrightBrowser;
}

async function closeBrowser(): Promise<void> {
  if (playwrightBrowser?.isConnected()) {
    try {
      await playwrightBrowser.close();
    } catch {
      // already closed
    }
    playwrightBrowser = null;
  }
}

const COOKIE_REFRESH_TTL_MS = 30 * 60 * 1000; // 30 min

/**
 * Refresh cookies for an account by navigating chat.qwen.ai in a real browser.
 *
 * @param cookieStr - Current saved cookies (may be stale)
 * @returns Fresh cookie string or null
 */
export async function refreshCookiesViaBrowser(cookieStr: string): Promise<string | null> {
  // Resolve the binary before the try block: a missing browser is an
  // environment fault, and must surface with its actionable message instead of
  // being flattened into a bare `null` by the catch below.
  resolveChromeExecutable();

  let page: any = null;
  try {
    const browser = await getBrowser();
    page = await browser.newPage();

    if (cookieStr) {
      const cookies = cookieStr.split(';').map((pair: string) => {
        const [name, ...rest] = pair.trim().split('=');
        return { name: name.trim(), value: rest.join('=').trim(), domain: '.chat.qwen.ai', path: '/' };
      });
      await page
        .context()
        .addCookies(cookies)
        .catch(() => {});
    }

    await page.goto(QWEN_API_BASE, { waitUntil: 'load', timeout: 25_000 }).catch(() => {});
    // Wait for WAF challenge to resolve (up to 15s)
    for (let i = 0; i < 15; i++) {
      const html = await page.evaluate(() => document.documentElement?.innerHTML || '').catch(() => '');
      if (!html.includes('aliyun_waf')) break;
      await new Promise((r) => setTimeout(r, 1000));
    }

    // The root page loads unchallenged, so on its own it never triggers the
    // WAF challenge that guards /api/** and never yields the tfstk/isg cookies
    // the API needs. Making the browser issue a real API request runs the
    // challenge JS in its own context, which sets those cookies.
    await page
      .evaluate(async (base: string) => {
        try {
          await fetch(`${base}/api/v2/users/status`, {
            method: 'GET',
            headers: { accept: 'application/json, text/plain, */*', source: 'web' },
            credentials: 'include',
          });
        } catch {
          // best effort — the cookies are what matter, not the response
        }
      }, QWEN_API_BASE)
      .catch(() => {});

    // AWSC sets tfstk/isg asynchronously after the challenge script runs, so
    // poll for them rather than reading cookies straight away.
    const WAF_COOKIES = ['tfstk', 'isg'];
    for (let i = 0; i < 12; i++) {
      const names = (await page.context().cookies()).map((c: any) => c.name);
      if (WAF_COOKIES.every((name) => names.includes(name))) break;
      await new Promise((r) => setTimeout(r, 500));
    }

    const freshCookies = await page.context().cookies();
    const cookieMap = new Map<string, string>();
    for (const c of freshCookies) {
      cookieMap.set(c.name, c.value);
    }

    const freshCookieStr = Array.from(cookieMap.entries())
      .map(([n, v]) => `${n}=${v}`)
      .join('; ');

    if (freshCookieStr) {
      logStore.log('info', 'fireyejs', `Cookies refreshed via browser: ${freshCookieStr.substring(0, 60)}...`);
      return freshCookieStr;
    }
    return null;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logStore.log('warn', 'fireyejs', `Cookie refresh via browser failed: ${msg.substring(0, 100)}`);
    return null;
  } finally {
    if (page) {
      try {
        await page.close();
      } catch {
        /* ignore */
      }
    }
  }
}
